# Use the official MySQL image
FROM mysql:latest

# Environment variables to initialize the database
ENV MYSQL_ROOT_PASSWORD=VxJEwTJG5CBwiaSe82i2MUA1c6MHp3Ce
ENV MYSQL_DATABASE=pactify
ENV MYSQL_USER=lepotekil
ENV MYSQL_PASSWORD=VxJEwTJG5CBwiaSe82i2MUA1c6MHp3Ce

# Expose the default MySQL port
EXPOSE 3306